# Generated by Django 5.0.6 on 2024-05-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0002_aboutcompany_glossaryquestion_news_vacancy_worker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryquestion',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
