# Generated by Django 5.0.6 on 2024-05-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0005_worker_image_worker_word_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='word_description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
