# Generated by Django 5.0.6 on 2024-05-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0006_alter_worker_word_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='word_description',
            new_name='work_description',
        ),
    ]
