# Generated by Django 5.0.6 on 2024-05-15 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0013_alter_review_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_rental_service_app.client'),
        ),
    ]
