# Generated by Django 5.0.6 on 2024-05-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0014_alter_review_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
