# Generated by Django 5.0.6 on 2024-05-16 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0016_alter_news_short_description_alter_news_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carextradition',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_extraditions', to='car_rental_service_app.client'),
        ),
    ]
