# Generated by Django 5.0.6 on 2024-05-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0018_carextradition_promocode_discount_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carextradition',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='carextradition',
            name='final_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='carextradition',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='carextradition',
            name='rental_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
