# Generated by Django 5.0.6 on 2024-05-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0021_alter_carextradition_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
