# Generated by Django 5.0.6 on 2024-05-16 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0023_carextradition_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='carextradition',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_rental_service_app.worker'),
        ),
    ]
