# Generated by Django 5.0.6 on 2024-05-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0024_carextradition_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carextradition',
            name='date_end',
            field=models.DateField(null=True),
        ),
    ]
