# Generated by Django 5.0.6 on 2024-05-17 15:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0025_alter_carextradition_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.AlterField(
            model_name='carextradition',
            name='number_days',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday_date',
            field=models.DateField(default='2000-01-01', validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 5, 22), message='Для регистрации необходимо достичь 18 лет')]),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(default='worker@email.by', max_length=40),
        ),
    ]
