# Generated by Django 5.0.6 on 2024-05-17 20:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0026_alter_car_daily_price_alter_car_price_alter_car_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carextradition',
            name='date_start',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 5, 17))]),
        ),
        migrations.AlterField(
            model_name='fine',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
