# Generated by Django 5.0.6 on 2024-05-18 10:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0027_alter_carextradition_date_start_alter_fine_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.IntegerField(default=0, max_length=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='carextradition',
            name='date_start',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 5, 18))]),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday_date',
            field=models.DateField(default='2000-01-01', validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 5, 23), message='Для регистрации необходимо достичь 18 лет')]),
        ),
    ]
