# Generated by Django 5.0.6 on 2024-05-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0015_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
