# Generated by Django 5.0.6 on 2024-05-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0017_alter_carextradition_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='carextradition',
            name='promocode',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='promocode',
            field=models.CharField(default='qwe', max_length=30),
            preserve_default=False,
        ),
    ]
