# Generated by Django 5.0.6 on 2024-05-16 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0019_alter_carextradition_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carextradition',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_rental_service_app.car'),
        ),
        migrations.AlterField(
            model_name='carextradition',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_extraditions', to='car_rental_service_app.client'),
        ),
    ]
