# Generated by Django 5.0.6 on 2024-05-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0022_car_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='carextradition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
