# Generated by Django 5.0.6 on 2024-09-09 23:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0028_client_age_alter_carextradition_date_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('site_url', models.URLField()),
                ('image', models.ImageField(default='news/no_image.png', upload_to='partners')),
            ],
        ),
        migrations.AlterField(
            model_name='carextradition',
            name='date_start',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 9, 10))]),
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday_date',
            field=models.DateField(default='2000-01-01', validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 9, 15), message='Для регистрации необходимо достичь 18 лет')]),
        ),
    ]
