# Generated by Django 5.0.6 on 2024-09-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0030_aboutcompany_certificate_aboutcompany_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
