# Generated by Django 5.0.6 on 2024-09-10 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0031_aboutcompany_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutCompany',
        ),
    ]
