# Generated by Django 5.0.6 on 2024-09-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0036_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qwe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisites', models.TextField(default='')),
                ('certificate', models.TextField(default='')),
            ],
        ),
    ]
