# Generated by Django 5.0.6 on 2024-09-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0041_companyinfo_video_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='certificate',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='history',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='video_src',
            field=models.CharField(default='', max_length=200),
        ),
    ]
