# Generated by Django 5.0.6 on 2024-05-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0004_alter_vacancy_description_alter_vacancy_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='image',
            field=models.ImageField(default='contacts/default_avatar.jpg', upload_to='contacts'),
        ),
        migrations.AddField(
            model_name='worker',
            name='word_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news/no_image.png', upload_to='news'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.CharField(max_length=50),
        ),
    ]
