# Generated by Django 5.0.6 on 2024-05-15 17:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0007_rename_word_description_worker_work_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='age',
        ),
        migrations.AddField(
            model_name='client',
            name='birthday_date',
            field=models.DateField(default="2000-01-01", validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 5, 20), message='Для регистрации необходимо достичь 18 лет')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(default='clients/default_avatar.jpg', upload_to='clients'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Вы ввели некорректный номер телефона', regex='^\\+\\d{9, 14}$')]),
        ),
    ]
