# Generated by Django 5.0.6 on 2024-05-15 18:13

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0008_remove_client_age_client_birthday_date_client_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday_date',
            field=models.DateField(default='2000-01-01', validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 5, 20), message='Для регистрации необходимо достичь 18 лет')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Вы ввели некорректный номер телефона', regex='^\\+\\d{9,14}$')]),
        ),
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(default='user@email.by', max_length=40),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Вы ввели некорректный номер телефона', regex='^\\+\\d{9,14}$')]),
        ),
    ]
