# Generated by Django 5.0.6 on 2024-05-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0009_worker_user_alter_client_birthday_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='bode_type',
            new_name='body_type',
        ),
    ]
