# Generated by Django 5.0.6 on 2024-05-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0011_alter_client_birthday_date_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
