# Generated by Django 5.0.6 on 2024-05-16 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0020_alter_carextradition_car_alter_carextradition_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carextradition',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car_rental_service_app.discount'),
        ),
    ]
