# Generated by Django 5.0.6 on 2024-09-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0029_partnercompany_alter_carextradition_date_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='certificate',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='history',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='logo',
            field=models.ImageField(default='news/no_image.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='requisites',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='video_src',
            field=models.FilePathField(default=''),
        ),
    ]
