# Generated by Django 5.0.6 on 2024-09-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0033_aboutcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='history',
            field=models.JSONField(default=dict),
        ),
    ]
