# Generated by Django 5.0.6 on 2024-09-10 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0034_alter_aboutcompany_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutCompany',
        ),
    ]
