# Generated by Django 5.0.6 on 2024-09-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0037_qwe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qwe',
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='history',
            field=models.JSONField(default=''),
        ),
    ]
