# Generated by Django 5.0.6 on 2024-09-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0039_remove_companyinfo_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='requisites',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='video_src',
        ),
    ]
