# Generated by Django 5.0.6 on 2024-09-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0040_remove_companyinfo_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='video_src',
            field=models.FilePathField(default=''),
        ),
    ]
