# Generated by Django 5.0.6 on 2024-09-29 22:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0042_companyinfo_certificate_companyinfo_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carextradition',
            name='date_start',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 9, 30))]),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday_date',
            field=models.DateField(default='2000-01-01', validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 10, 5), message='Для регистрации необходимо достичь 18 лет')]),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
